# Generated by Django 4.2.1 on 2023-05-24 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_alter_task_test_alter_taskoption_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.test'),
        ),
        migrations.AlterField(
            model_name='taskoption',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='tests.task'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.test'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
